### ISSUE TITLE
Use watch option for tsc

### ISSUE THREAD

**Issue by Keats** [kotas/gulp-tsc#23]
Hello,

I'm trying gulp-tsc and it seems when you're watching, it restarts the compiler every time a file changes (and it takes about 2-3s on my machine).

Is it possible to have an option to start the compiler with the -w option as it should be much faster.

I'll have a look at the code later this week but let me know what you think of it

**Comment by kotas** [comment]
Thank you for proposal!

Actually, I was wondering if it is needed for gulp-tsc since it will obviously reduce the compilation time. However, according to [gulp plugin guideline](https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md), a gulp plugin is not encouraged to do a thing which can be done easily with other plugins, and there is gulp-watch for that. 

Plus, I'm not sure gulp-tsc can capture output files from tsc command with -w option continuously, which seems to be kind of hard since it will require to parse output messages from tsc command.

2-3 secs for each compile is acceptable for me so I was not _motivated_ to implement that option. But if you need it, I'll try to implement it when I have a time. Your patch is also welcome. Thanks :)

**Comment by Keats** [comment]
I'll look into it this weekend.

For the gulp.watch thing gulp-karma (https://www.npmjs.org/package/gulp-karma) uses the karma watcher instead.

I'm not sure how tsc -w works too much, just saw the option in the help.

Cheers

**Comment by Keats** [comment]
I just tried the watch option a bit, it doesn't seem that much faster that normal compilation so I guess I'll just go with the 'restart the compiler' approach then (unless you have a good idea on how to improve it).  
Apparently the time doesn't grow too much when the project grows so that should be ok.

**Comment by kotas** [comment]
Oh, sorry I missed your reply for long. And thank you for additional investigation!

I agree with your conclusion and I think I won't add the watch option to gulp-tsc for now.

IMO, the watch option would have reduced the initialization time of tsc command, but it doesn't help with the compilation time which is the most part of compilation. I think that's why the watch option is not effective.

Once TypeScript gets mature, someone will make an alternative implementation of the compiler in C or something, which will dramatically reduce the compilation time!
